=== 安装Elasticsearch

最简单的能知道Elasticsearch能为你做什么的方式就是尝试去用它，所以让我们开始吧！

安装Elasticsearch的唯一要求就是一个比较新的Java。最好是从 http://www.java.com[wwww.java.com]安装一个官方Java的最新版本.
你可以从 http://www.elasticsearch.org/download/[elasticsearch.org/download]下载Elasticsearch的最新版本。

[source,sh]
--------------------------------------------------
curl -L -O http://download.elasticsearch.org/PATH/TO/LATEST/$VERSION.zip
unzip elasticsearch-$VERSION.zip
cd  elasticsearch-$VERSION
--------------------------------------------------

提示: 当你在生产环境安装Elasticsearch时，你可以使用上面的方法，或者是 http://www.elasticsearch.org/downloads[下载页面]
上的Debian或者RPM安装包。或者你也可以使用官方提供的 https://github.com/elasticsearch/puppet-elasticsearch[Puppet] 或者
 https://github.com/elasticsearch/cookbook-elasticsearch[Chef cookbook].

[[marvel]]
==== 安装Marvel

http://www.elasticsearch.com/marvel)[Marvel] 是一个管理和监控Elasticsearch的工具，它是免费给开发者使用的。它和一个名为
Sense的交互控制台配合使用，使得从浏览器监控和管理elasticsearch变得十分简单。

这本书的许多示例代码都包含一个  ``View in Sense'' 链接。当你点击它的时候，它将在Sense控制台打开这个代码的运行例子。你不
是非需要安装Marvel不可，但是安装了Marvel能够使你和这本书能够更好的互动，它让你能够很方便的在你的本地Elasticsearch集群试
验书中的例子代码。

Marvel是一个插件。可以在Elasticsearch的目录使用如下的命令下载和安装它：

[source,js]
--------------------------------------------------
./bin/plugin -i elasticsearch/marvel/latest
--------------------------------------------------

你可能不想让Marvel去监控你的本地集群，你可以使用下面的代码让Marvel不生效：

[source,js]
--------------------------------------------------
echo 'marvel.agent.enabled: false' >> ./config/elasticsearch.yml
--------------------------------------------------

==== 运行Elasticsearch

Elasticsearch已经蓄势待发，现在你便可以运行它了：

[source,js]
--------------------------------------------------
./bin/elasticsearch
--------------------------------------------------

如果你想让它在后台保持运行的话可以在命令后面再加一个 `-d`

启动后你就可以使用另一个终端窗口来进行测试了:

[source,js]
--------------------------------------------------
curl 'http://localhost:9200/?pretty'
--------------------------------------------------


你应该看到如下提示：

[source,js]
--------------------------------------------------
{
   "status": 200,
   "name": "Shrunken Bones",
   "version": {
      "number": "1.1.0",
      "lucene_version": "4.7"
   },
   "tagline": "You Know, for Search"
}
--------------------------------------------------
// SENSE: 010_Intro/10_Info.json

这就说明你的Elasticsearch _群集_ 已经上线运行了，这时我们就可以进行各种实验了。

.集群和节点
----
 _节点_是Elasticsearch运行的实例。_集群_是一组有着同样`cluster.name`的节点，它们协同工作，互相分享数据，提供了故障转移和扩展的功能。当然一个节点也可以是一个集群。
----
