[[mapping-analysis]]
== 映射和分析

在随意测试使用索引里面的数据的时候, 我们注意到一些奇怪的事情。
一些数据好像不对: 我们有12条推特在我们的索引里, 并且只有1条推特包含时间串
`2014-09-15`, 但是看看下面命中的查询:

[source,js]
--------------------------------------------------
GET /_search?q=2014              # 12 results
GET /_search?q=2014-09-15        # 12 results !
GET /_search?q=date:2014-09-15   # 1  result
GET /_search?q=date:2014         # 0  results !
--------------------------------------------------
// SENSE: 052_Mapping_Analysis/25_Data_type_differences.json

为什么在整个 `date` 上查询 <<all-field-intro,`_all` field>> 返回所有的推特，
但是在 `date` 字段查询年份的时候没有推特返回？
为什么在 `_all` 字段查询和在 `date` 字段查询结果不一样?

Presumably it is because the way our data has been indexed in the `_all`
field is different to how it has been indexed in the `date` field.
So let's take a look at how Elasticsearch has interpreted our document
structure, by requesting the _mapping_ (or schema definition)
for the `tweet` type in the `gb` index:

[source,js]
--------------------------------------------------
GET /gb/_mapping/tweet
--------------------------------------------------
// SENSE: 052_Mapping_Analysis/25_Data_type_differences.json


which gives us:

[source,js]
--------------------------------------------------
{
   "gb": {
      "mappings": {
         "tweet": {
            "properties": {
               "date": {
                  "type": "date",
                  "format": "dateOptionalTime"
               },
               "name": {
                  "type": "string"
               },
               "tweet": {
                  "type": "string"
               },
               "user_id": {
                  "type": "long"
               }
            }
         }
      }
   }
}
--------------------------------------------------


Elasticsearch has dynamically generated a mapping for us, based on what it
could guess about our field types. The response shows us that the `date` field
has been recognised as a field of type `date`. The `_all` field isn't
mentioned because it is a default field, but we know that the `_all` field is
of type `string`.

So fields of type `date` and fields of type `string` are indexed differently,
and can thus be searched differently.  That's not entirely surprising.
You might expect that each of the core data types -- strings, numbers, booleans
and dates -- might be indexed slightly differently. And this is true:
there are slight differences.

But by far the biggest difference is actually between fields that represent
_exact values_ (which can include `string` fields) and fields that
represent _full text_. This distinction is really important -- it's the thing
that separates a search engine from all other databases.

