[[mapping-analysis]]
== mapping和analysis

在随意测试使用索引里面的数据的时候, 我们注意到一些奇怪的事情。
一些数据好像不对: 我们有12条推特在我们的索引里, 并且只有1条推特包含时间串
`2014-09-15`, 但是看看下面命中的查询:

[source,js]
--------------------------------------------------
GET /_search?q=2014              # 12 results
GET /_search?q=2014-09-15        # 12 results !
GET /_search?q=date:2014-09-15   # 1  result
GET /_search?q=date:2014         # 0  results !
--------------------------------------------------
// SENSE: 052_Mapping_Analysis/25_Data_type_differences.json

为什么在整个 `date` 上查询 <<all-field-intro,`_all` field>> 返回所有的推特，
但是在 `date` 字段查询年份的时候没有推特返回？
为什么在 `_all` 字段查询和在 `date` 字段查询结果不一样?

推测起来可能是因为我们的数据在 `_all` 字段和 `date` 字段上索引的不一样。
所以，通过请求 `gb` index中 `tweet` type的 _mapping_ (或者说是模式定义)
来看看ElasticSearch是怎么解释document结构的。

[source,js]
--------------------------------------------------
GET /gb/_mapping/tweet
--------------------------------------------------
// SENSE: 052_Mapping_Analysis/25_Data_type_differences.json


执行上面的命令，我们得到的结果如下:

[source,js]
--------------------------------------------------
{
   "gb": {
      "mappings": {
         "tweet": {
            "properties": {
               "date": {
                  "type": "date",
                  "format": "dateOptionalTime"
               },
               "name": {
                  "type": "string"
               },
               "tweet": {
                  "type": "string"
               },
               "user_id": {
                  "type": "long"
               }
            }
         }
      }
   }
}
--------------------------------------------------


ElasticSearch为我们的数据动态生成mapping，基于mapping它能猜测到我们的数据类型.
结果显示， `date` 字段被识别成一个类型是 `date` 的字段。 `_all` 字段没提及是因
为它是一个默认字段，但是我们知道 `_all` 字段是 `string` 类型的。 

所以 `date` 类型的字段和 `string` 类型的字段的索引方式是不同的，因此搜索也不一样。
那并不是完全出人意料。你可能觉得这些核心数据类型 -- strings, numbers, boolens和
dates -- 的索引方式会有些略微不同。是的，它们确实有些不一样。

但是到现在为止最大不同是在那些代表 _exact_values_ (包括 `string` 字段)的字段和i
代表 _full_text_ 的字段之间。这些差别非常重要 -- 这些不同把这个引擎和其他别的数
据库区分了开来。

